Miscellaneous bugfixs from release
perfectsense/gyro-azure-provider pull request #155
Opened 2024-08-12 16:02 UTC by harjain99

- Fixes subnet creation
  - Networks were created with a default subnet covering the entire network range if one wasn't provided
  - this made it impossible to create other subnets
  - the fix was to specify subnets in the network creation call
- The `enableMultipleStandardLoadBalancers` in the K8s cluster network profile was getting a default value set, which is no longer supported by the api.
- Fixes public container creation
  - There is a delay for the StorageAccount to actually become public.
  - Unfortunately the api doesn't really provide a good way to determine if the account is actually public.
  - The fix was to add a wait/retry on the container creation call which results in a 409 error if the creation isn't successful

2024-08-12 17:17 UTC, tloisel1 commented
Code review looks okay

2024-08-13 16:17 UTC, deepanjan90 requested changes
One inline comment

2024-08-13 16:17 UTC, deepanjan90 commented on src/main/java/gyro/azure/storage/CloudBlobContainerResource.java
> +
We should look into verifying the storage account is set to `public` and get the error when creating this container with public access to fire the retry logic.

That way any other error bubbles up and we have a direct condition for retrying

2024-08-13 21:46 UTC, deepanjan90 approved these changes

2024-08-13 21:46 UTC, merged